---

- name: Gather frr bgp ipv4 peers
  ansible.builtin.command: vtysh -c "show ip bgp summ json"
  register: frr_bgp_ipv4_cmd
  changed_when: false
  tags: [not_print_action]

- name: Gather frr bgp ipv6 peers
  ansible.builtin.command: vtysh -c "show bgp ipv6 summ json"
  register: frr_bgp_ipv6_cmd
  changed_when: false
  tags: [not_print_action]

- name: Set bgp peers facts
  ansible.builtin.set_fact:
    frr_bgp_ipv4: "{{ (frr_bgp_ipv4_cmd.stdout | from_json).ipv4Unicast.peers | default({}) }}"
    frr_bgp_ipv6: "{{ (frr_bgp_ipv6_cmd.stdout | from_json).ipv6Unicast.peers | default({}) }}"
    frr_asnum: "{{ (frr_bgp_ipv4_cmd.stdout | from_json).ipv4Unicast.as | default(59238) }}"
  tags: [not_print_action]
