---

- name: Make sure there's no peer if not in peergroup {{ peer.ip }}
  ansible.builtin.shell:
    cmd: |
      vtysh -c "conf t
      router bgp {{ frr_bgp.asnum }}
      no neighbor {{ peer_member.ip }}
      "
  when: '" neighbor " ~ peer_member.ip ~ " peer-group " ~ peer.ip not in frr_config.stdout_lines'
  changed_when: true
  notify: save frr config

- name: Add peergroup member (plain)
  ansible.builtin.shell:
    cmd: |
      vtysh -c "conf t
      router bgp {{ frr_bgp.asnum }}
      neighbor {{ item }} peer-group {{ peer.ip }}
      "
  with_items: "{{ peer.members }}"
  when: item | ansible.builtin.type_debug != 'dict' and " neighbor " ~ item ~ " peer-group " ~ peer.ip not in frr_config.stdout_lines
  changed_when: true
  notify: save frr config

- name: Add peergroup member with informations
  ansible.builtin.include_tasks: frr_bgp_peers_peergroup_member_detail.yml
  loop: "{{ peer.members }}"
  loop_control:
    loop_var: peer_member
  when: peer_member | ansible.builtin.type_debug == 'dict'
