---

- name: Make sure there's no peer if not in peergroup {{ peer.ip }}
  ansible.builtin.shell:
    cmd: |
      vtysh -c "conf t
      router bgp {{ frr_bgp.asnum }}
      no neighbor {{ peer_member.ip }}
      "
  when: '" neighbor " ~ peer_member.ip ~ " peer-group " ~ peer.ip not in frr_config.stdout_lines'
  changed_when: true
  notify: save frr config

- name: Add peergroup member {{ peer_member.ip ~ " to " ~ peer.ip }}
  ansible.builtin.shell:
    cmd: |
      vtysh -c "conf t
      router bgp {{ frr_bgp.asnum }}
      neighbor {{ peer_member.ip }} peer-group {{ peer.ip }}
      "
  when: '" neighbor " ~ peer_member.ip ~ " peer-group " ~ peer.ip not in frr_config.stdout_lines'
  changed_when: true
  notify: save frr config

- name: Add peergroup member description {{ peer_member.ip }}
  ansible.builtin.shell:
    cmd: |
      vtysh -c "conf t
      router bgp {{ frr_bgp.asnum }}
      neighbor {{ peer_member.ip }} description {{ peer_member.desc }}
      "
  when: 'peer_member.desc is defined and " neighbor " ~ peer_member.ip ~ " description " ~ peer_member.desc not in frr_config.stdout_lines'
  changed_when: true
  notify: save frr config

- name: Add peergroup member remote-as {{ peer_member.ip }}
  ansible.builtin.shell:
    cmd: |
      vtysh -c "conf t
      router bgp {{ frr_bgp.asnum }}
      neighbor {{ peer_member.ip }} remote-as {{ peer_member.remote_as }}
      "
  when: 'peer_member.remote_as is defined and " neighbor " ~ peer_member.ip ~ " remote-as " ~ peer_member.remote_as not in frr_config.stdout_lines'
  changed_when: true
  notify: save frr config


- name: Set peergroup member maximum prefix {{ peer_member.ip }}
  ansible.builtin.shell:
    cmd: |
      vtysh -c "conf t
      router bgp {{ frr_bgp.asnum }}
      address-family {{ peer.address_family }} unicast
      neighbor {{ peer_member.ip }} maximum-prefix {{ peer_member.maximum_prefix }}
      "
  when: 'peer_member.maximum_prefix is defined and
    "  neighbor " ~ peer_member.ip ~ " maximum-prefix " ~ peer_member.maximum_prefix not in frr_config.stdout_lines'
  changed_when: true
  notify: save frr config

- name: Set peergroup member maximum prefix out {{ peer_member.ip }}
  ansible.builtin.shell:
    cmd: |
      vtysh -c "conf t
      router bgp {{ frr_bgp.asnum }}
      address-family {{ peer.address_family }} unicast
      neighbor {{ peer_member.ip }} maximum-prefix-out {{ peer_member.maximum_prefix_out }}
      "
  when: 'peer_member.maximum_prefix_out is defined and
    "  neighbor " ~ peer_member.ip ~ " maximum-prefix-out " ~ peer_member.maximum_prefix_out not in frr_config.stdout_lines'
  changed_when: true
  notify: save frr config
