---
- name: Gather frr config
  ansible.builtin.command: vtysh -c "show run"
  register: frr_config
  changed_when: false

- name: Gather bgp facts
  ansible.builtin.import_tasks: frr_facts_bgp.yml
  when: '"\nrouter bgp " in frr_config.stdout'
