- name: Gather frr facts
  ansible.builtin.import_tasks: frr_facts.yml
  tags: [frr, frr-config, frr-bgp, always]

- name: Configure frr bgp
  ansible.builtin.import_tasks: frr_bgp.yml
  when: frr_bgp is defined and frr_bgp.asnum is defined
  tags: [frr, frr-config, frr-bgp]

- name: Configure frr bgp peers
  ansible.builtin.import_tasks: frr_bgp_peers.yml
  when: frr_bgp is defined and frr_bgp.peers is defined
  tags: [frr, frr-config, frr-bgp]
