---
- name: Check current route-map setting for {{ routemap.name }} # noqa: risky-shell-pipe
  ansible.builtin.shell:
    vtysh -c "show run" | sed -n '/^route-map {{ routemap.name }} /,/^!$/p'
  register: routemap_config_all
  changed_when: false
  tags: [frr-routemap, not_print_action]

- name: Generate route-map entries for {{ routemap.name }}
  ansible.builtin.template:
    src: "route-map-entries.j2"
    dest: "/tmp/route-map-entries-{{ routemap.name }}"
    mode: "0600"
  changed_when: false
  tags: [frr-routemap]

- name: Execute route-map set command for {{ routemap.name }}
  ansible.builtin.shell:
    cmd: |
      grep -E "^ " /tmp/route-map-entries-{{ routemap.name }} > /dev/null && (vtysh -f /tmp/route-map-entries-{{ routemap.name }} || exit 2)
  register: routemap_execution
  changed_when: routemap_execution.rc == 0
  failed_when: routemap_execution.rc > 1
  notify: save frr config
  tags: [frr-routemap]
