---
- name: route-map {{ routemap.name }} {{ rm_entry.sequence }}/ check current route-map setting
  shell:
    vtysh -c "show run" | sed -n '/^route-map {{ routemap.name }} [^ ]* {{ rm_entry.sequence }}$/,/^!$/p'
  register: routemap_config
  changed_when: false
  tags: [ frr-routemap, not_print_action ]

- name: route-map {{ routemap.name }} {{ rm_entry.sequence }}/ generate new route-map setting
  template:
    src: "route-map-entry.j2"
    dest: "/tmp/route-map-{{ routemap.name }}-{{ rm_entry.sequence }}"
    mode: 0600
  changed_when: false
  tags: [ frr-routemap ]

- name: route-map {{ routemap.name }} {{ rm_entry.sequence }}/ really execute route-map set command
  shell:
    cmd: |
      cat /tmp/route-map-{{ routemap.name }}-{{ rm_entry.sequence }} | vtysh
      [ $(cat /tmp/route-map-{{ routemap.name }}-{{ rm_entry.sequence }} | wc -l) -gt 2 ] || echo "no change"
  register: routemap_execution
  changed_when: "'no change' not in routemap_execution.stdout_lines"
  notify: save frr config
  tags: [ frr-routemap ]
