---
# tasks file for frr-routemap

- name: Configure frr route-map
  ansible.builtin.include_tasks: frr_routemap_setting.yml
  loop: "{{ frr_routemaps }}"
  loop_control:
    loop_var: routemap
  tags: [frr, frr-config, frr-bgp, frr-routemap]
