---
- name: prefix-list {{ prefixlist.address_family }} {{ prefixlist.name }}/ check for current entries
  shell:
    vtysh -c "show run" | grep -E "^{{ 'ipv6' if prefixlist.address_family == 'ipv6' else 'ip' }} prefix-list {{ prefixlist.name }} seq " | grep -oE 'permit .*' | sed 's/permit //g'
  register: prefixlist_config
  changed_when: false
  tags: [ not_print_action ]


- name: prefix-list {{ prefixlist.address_family }} {{ prefixlist.name }}/generate prefixlist entries
  template:
    src: "prefix-list-entries.j2"
    dest: "/tmp/prefix-list-{{ prefixlist.address_family }}-{{ prefixlist.name }}"
    mode: 0600
  changed_when: false

- name: prefix-list {{ prefixlist.address_family }} {{ prefixlist.name }}/ execute prefix-list set command
  shell:
    cmd: |
      grep " prefix-list " /tmp/prefix-list-{{ prefixlist.address_family }}-{{ prefixlist.name }} > /dev/null && (vtysh -f /tmp/prefix-list-{{ prefixlist.address_family }}-{{ prefixlist.name }} || exit 2)
  register: prefixlist_execution
  changed_when: prefixlist_execution.rc == 0
  failed_when: prefixlist_execution.rc > 1
  notify: save frr config
