---
- name: prefix-list {{ prefixlist.name }}/ check for current entries
  shell:
    vtysh -c "show run" | grep -E "^{{ 'ipv6' if prefixlist.address_family == 'ipv6' else 'ip' }} prefix-list {{ prefixlist.name }} seq " | grep -oE 'permit .*' | sed 's/permit //g'
  register: prefixlist_config
  changed_when: false
  tags: [ not_print_action ]

- name: prefix-list {{ prefixlist.name }}/ add missing entries
  shell:
    cmd: |
      vtysh -c "conf t
      {{ 'ipv6' if prefixlist.address_family == 'ipv6' else 'ip' }} prefix-list {{ prefixlist.name }} permit {{ prefix }}"
  loop: "{{ prefixlist.entries }}"
  loop_control:
    loop_var: prefix
  when: prefix not in prefixlist_config.stdout_lines
  notify: save frr config

- name: prefix-list {{ prefixlist.name }}/ remove unused entries
  shell:
    cmd: |
      vtysh -c "conf t
      no {{ 'ipv6' if prefixlist.address_family == 'ipv6' else 'ip' }} prefix-list {{ prefixlist.name }} permit {{ item }}"
  loop: "{{ prefixlist_config.stdout_lines }}"
  when: prefixlist_config.stdout_lines is defined and item not in prefixlist.entries
  notify: save frr config
