---

- name: Gather ipv4 prefixes for as-set {{ as_set_config.as_set }}
  ansible.builtin.command: bgpq4 -4 -A -m 24 -F "%n/%l ge %a le %A\n" -h {{ frr_irrd_server }} {{ as_set_config.as_set }}
  register: irrv4
  delegate_to: localhost
  changed_when: false

- name: Gather ipv6 prefixes for as-set {{ as_set_config.as_set }}
  ansible.builtin.command: bgpq4 -6 -A -m 48 -F "%n/%l ge %a le %A\n" -h {{ frr_irrd_server }} {{ as_set_config.as_set }}
  register: irrv6
  delegate_to: localhost
  changed_when: false

- name: Run frr-prefixlist role
  ansible.builtin.include_role:
    name: frr-prefixlist
    apply:
      tags: frr-as-sets
  vars:
    frr_prefixlists:
      - name: "{{ as_set_config.name }}"
        address_family: ipv4
        entries: "{{ irrv4.stdout_lines }}"
      - name: "{{ as_set_config.name }}"
        address_family: ipv6
        entries: "{{ irrv6.stdout_lines }}"
