---
- name: as-set {{ as_set_config.as_set }}/ gather ipv4 prefixes
  command: bgpq4 -4 -A -F "%n/%l\n" -m 24 -h {{ frr_irrd_server }} {{ as_set_config.as_set }}
  register: irrv4
  changed_when: false

- name: as-set {{ as_set_config.as_set }}/ gather ipv6 prefixes
  command: bgpq4 -6 -A -F "%n/%l\n" -m 48 -h {{ frr_irrd_server }} {{ as_set_config.as_set }}
  register: irrv6
  changed_when: false

- name: run frr-prefixlist role
  import_role:
    name: frr-prefixlist
  vars: 
    frr_prefixlists:
    - name: "{{ as_set_config.name }}"
      address_family: ipv4
      entries: "{{ irrv4.stdout_lines }}"
    - name: "{{ as_set_config.name }}"
      address_family: ipv6
      entries: "{{ irrv6.stdout_lines }}"